### ISSUE TITLE
overlap between extra-modules.conf and ubuntu-core-initramfs.conf

### ISSUE THREAD

**Issue by kubiko** [snapcore/core-initrd#134]
version: ubuntu core 22
Using combination of
- extra modules in `${skeleton}/modules/main/extra-modules.conf`
- configured modules to be loaded by systemd in `${skeleton}/main/usr/lib/modules-load.d/ubuntu-core-initramfs.conf`

If those two lists contain the same kernel module(s), it makes `ubuntu-core-initramfs create-initrd` fail with the following error:
```
Traceback (most recent call last):
  File "/home/ondrak/kernel-snap/parts/kernel/build/ubuntu-core-initramfs/usr/bin/ubuntu-core-initramfs", line 490, in <module>
    main()
  File "/home/ondrak/kernel-snap/parts/kernel/build/ubuntu-core-initramfs/usr/bin/ubuntu-core-initramfs", line 486, in main
    globals()[args.subcmd.replace("-", "_")](parser, args)
  File "/home/ondrak/kernel-snap/parts/kernel/build/ubuntu-core-initramfs/usr/bin/ubuntu-core-initramfs", line 310, in create_initrd
    add_modules_from_file(main, kernel_root, modules, firmware, module_load, db,
  File "/home/ondrak/kernel-snap/parts/kernel/build/ubuntu-core-initramfs/usr/bin/ubuntu-core-initramfs", line 251, in add_modules_from_file
    db.mark_installed(module, conf_file)
  File "/home/ondrak/kernel-snap/parts/kernel/build/ubuntu-core-initramfs/usr/bin/ubuntu-core-initramfs", line 135, in mark_installed
    elif old_mode == ModuleDb.IMPLICIT:
AttributeError: type object 'ModuleDb' has no attribute 'IMPLICIT'
```

**Comment by alfonsosanchezbeato** [comment]
Fixed by https://github.com/snapcore/core-initrd/pull/135

**Comment by kubiko** [comment]
thank you @alfonsosanchezbeato!
